package cn.lp.bean;

public class TProblem0 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem0.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem0.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem0.id
     *
     * @return the value of t_problem0.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem0.id
     *
     * @param id the value for t_problem0.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem0.content
     *
     * @return the value of t_problem0.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem0.content
     *
     * @param content the value for t_problem0.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}