package cn.lp.dal.mapper;

import cn.lp.bean.TProblem0;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;
@Mapper
public interface TProblem0Mapper extends BaseMapper<TProblem0> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem0
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem0
     *
     * @mbg.generated
     */
    @Override
    int insert(TProblem0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem0
     *
     * @mbg.generated
     */
    TProblem0 selectByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem0
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TProblem0 record);
    @Select("select count(*) from t_problem")
    int count();
}